name: Release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+"

env:
  PLUGIN_NAME: obsidian-file-cleaner-redux
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: npm ci

      - name: Run build
        run: npm run build

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            main.js
            manifest.json

  create-github-release:
    name: Create release
    runs-on: ubuntu-latest

    needs: build

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{github.ref}} --generate-notes --prerelease \
            main.js \
            manifest.json
